# Site settings
author: Veronica Bustabad
title: My Journey as a Student with the Flatiron School
header-img: img/home-bg.png
email: vbustabad@gmail.com
copyright_name: Veronica Bustabad
description: > # this means to ignore newlines until "baseurl:"
  Best Practices, Tips and Advice for Learning How to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  vbustabad

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
